---
#
- name: Create configuration directory
  file:
    path: "{{ geth_config_dir }}"
    state: directory
    owner: "{{ geth_user }}"
    group: "{{ geth_group }}"
    recurse: yes
  become: true

- name: Create data directory
  file:
    path: "{{ geth_data_dir }}"
    state: directory
    owner: "{{ geth_user }}"
    group: "{{ geth_group }}"
    recurse: no
  become: true
