---
- name: Create geth systemd service
  ansible.builtin.template:
    src: "{{ geth_systemd_template }}"
    dest: "{{ geth_systemd_dir }}/geth.service"
    owner: "root"
    group: "root"
  become: true
  when: ( geth_managed_service ) and
    ( ansible_os_family != "Darwin" )
  register: systemd_file

- name: Set updated optionally to trigger a systemd restart at the end
  ansible.builtin.set_fact:
    geth_state_updates: "{{ geth_state_updates + ['geth.systemd_file'] }}"
  when: systemd_file is changed

- name: Reload systemd to reread configs
  ansible.builtin.systemd:
    daemon_reload: yes
  become: true
  when: systemd_file is changed

- name: Enable and start geth service
  ansible.builtin.systemd:
    name: geth
    state: "{{ geth_systemd_state }}"
    enabled: "{{ (geth_systemd_state!='stopped') | ternary('true', 'false') | bool }}"
  become: true
  when: ( geth_state_updates|length > 0 ) and
    ( geth_managed_service ) and
    ( ansible_os_family != "Darwin" )
